### ISSUE TITLE
Taxonomy fieldtype max_items: 1 not working

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-docs#110]
[From the docs](https://docs.statamic.com/fieldtypes/relate):

> The maximum number of items that may be selected. Setting this to 1 will change the UI to a dropdown.

Here's my YAML:

```
          filter_by_keyword:
            display: News Category Filter
            instructions: Select a keyword to apply a filter.
            type: taxonomy
            taxonomy: news-categories
            max_items: 1
            width: 50
          filter_by_category:
            display: Events Category Filter
            instructions: Select a keyword to apply a filter.
            type: taxonomy
            taxonomy: events-categories
            max_items: 1
            width: 50
```

and my resultant Markdown:

```
    filter_by_keyword:
      - 8498e2e3-b88d-417a-a6ea-af20f18e888f
    filter_by_category:
      - 97f76385-42de-4511-83e3-444f354f19b0
```
