### ISSUE TITLE
Wrong file location in the Macro documentation

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-docs#12]
http://docs.talonsbeard.com/docs/modifiers#string:macro

_Those groups are each called a “macro” and are stored in your theme’s `settings/macro.yaml` file._

Should be 

_Those groups are each called a “macro” and are stored in your theme’s `settings/macros.yaml` file._

Also

```
# /site/theme/<your_theme>/settings/macro.yaml
macros:
  headline:
    title: true
    widont: true
    remove_right: .
```

should be

```
# /site/themes/<your_theme>/settings/macros.yaml
headline:
  title: true
  widont: true
  remove_right: .
```
