### ISSUE TITLE
Form fieldset doesn't seem documented

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-docs#231]
https://docs.statamic.com/fieldtypes doesn't mention a form field (that I can see)

the CP generator makes this though:

```
fields:
  my_form:
    type: form
    display: My Form
```
