### ISSUE TITLE
Fieldsets validate rules for files

### ISSUE THREAD

**Issue by jeromecoupe** [statamic/v2-docs#26]
Here is my fieldset config for an asset file

``` yaml
fields:
  cover_image:
    type: assets
    display: Cover Image
    instructions: Choose or upload an image for your blogpost
    validate: required|image|max:1024
    container: 380dc8d9-481c-4d18-9162-ecd5688f98a8
    folder: blog-images
    max_files: 1
```

Unless I am mistaken [that's the required syntax](https://laravel.com/docs/5.1/validation) to require the file to be an image of less that 1MB but when I try to save an entry, the control panel displays the following message:

"The Cover Image field must be an image."

The file is an image with `jpeg` or `jpg` extension
